
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "ApuracaoEletronica", IsSet = false)]
    public class ApuracaoEletronica : IASN1PreparedElement 
    {
        
        private TipoApuracao tipoapuracao_;
        
		[ASN1Element(Name = "tipoapuracao", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public TipoApuracao Tipoapuracao
        {
            get { return tipoapuracao_; }
            set { tipoapuracao_ = value;  }
        }
  
        private MotivoApuracaoEletronica motivoApuracao_;
        
		[ASN1Element(Name = "motivoApuracao", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public MotivoApuracaoEletronica MotivoApuracao
        {
            get { return motivoApuracao_; }
            set { motivoApuracao_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ApuracaoEletronica));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
