
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "CargoConstitucional")]
    public class CargoConstitucional : IASN1PreparedElement 
    {
        public enum EnumType 
        {
            
            [ASN1EnumItem ( Name = "presidente", HasTag = true , Tag = 1 )]
            presidente , 
            [ASN1EnumItem ( Name = "vicePresidente", HasTag = true , Tag = 2 )]
            vicePresidente , 
            [ASN1EnumItem ( Name = "governador", HasTag = true , Tag = 3 )]
            governador , 
            [ASN1EnumItem ( Name = "viceGovernador", HasTag = true , Tag = 4 )]
            viceGovernador , 
            [ASN1EnumItem ( Name = "senador", HasTag = true , Tag = 5 )]
            senador , 
            [ASN1EnumItem ( Name = "deputadoFederal", HasTag = true , Tag = 6 )]
            deputadoFederal , 
            [ASN1EnumItem ( Name = "deputadoEstadual", HasTag = true , Tag = 7 )]
            deputadoEstadual , 
            [ASN1EnumItem ( Name = "deputadoDistrital", HasTag = true , Tag = 8 )]
            deputadoDistrital , 
            [ASN1EnumItem ( Name = "primeiroSuplenteSenador", HasTag = true , Tag = 9 )]
            primeiroSuplenteSenador , 
            [ASN1EnumItem ( Name = "segundoSuplenteSenador", HasTag = true , Tag = 10 )]
            segundoSuplenteSenador , 
            [ASN1EnumItem ( Name = "prefeito", HasTag = true , Tag = 11 )]
            prefeito , 
            [ASN1EnumItem ( Name = "vicePrefeito", HasTag = true , Tag = 12 )]
            vicePrefeito , 
            [ASN1EnumItem ( Name = "vereador", HasTag = true , Tag = 13 )]
            vereador , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CargoConstitucional));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
