
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "Eleicoes")]
    public class Eleicoes : IASN1PreparedElement 
    {
        
        private System.Collections.Generic.ICollection<EleicaoVota> eleicoesVota_;
        private bool  eleicoesVota_selected = false;

        
		[ASN1SequenceOf(Name = "eleicoesVota", IsSetOf = false)]
    
		[ASN1Element(Name = "eleicoesVota", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<EleicaoVota> EleicoesVota
        {
            get { return eleicoesVota_; }
            set { selectEleicoesVota(value); }
        }
  
        private System.Collections.Generic.ICollection<EleicaoSA> eleicoesSA_;
        private bool  eleicoesSA_selected = false;

        
		[ASN1SequenceOf(Name = "eleicoesSA", IsSetOf = false)]
    
		[ASN1Element(Name = "eleicoesSA", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<EleicaoSA> EleicoesSA
        {
            get { return eleicoesSA_; }
            set { selectEleicoesSA(value); }
        }
  
        public bool isEleicoesVotaSelected()
        {
            return this.eleicoesVota_selected;
        }

        

        public void selectEleicoesVota (System.Collections.Generic.ICollection<EleicaoVota> val) 
        {
            this.eleicoesVota_ = val;
            this.eleicoesVota_selected = true;
            
            this.eleicoesSA_selected = false;
            
        }
  
        public bool isEleicoesSASelected()
        {
            return this.eleicoesSA_selected;
        }

        

        public void selectEleicoesSA (System.Collections.Generic.ICollection<EleicaoSA> val) 
        {
            this.eleicoesSA_ = val;
            this.eleicoesSA_selected = true;
            
            this.eleicoesVota_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Eleicoes));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
