
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "EleicaoSA", IsSet = false)]
    public class EleicaoSA : IASN1PreparedElement 
    {
        
        private IDEleicao idEleicao_;
        
		[ASN1Element(Name = "idEleicao", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public IDEleicao IdEleicao
        {
            get { return idEleicao_; }
            set { idEleicao_ = value;  }
        }
  
        private TipoCedulaSA tipoCedulaSA_;
        
		[ASN1Element(Name = "tipoCedulaSA", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public TipoCedulaSA TipoCedulaSA
        {
            get { return tipoCedulaSA_; }
            set { tipoCedulaSA_ = value;  }
        }
  
        private OrigemVotosSA origemVotosSA_;
        
		[ASN1Element(Name = "origemVotosSA", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public OrigemVotosSA OrigemVotosSA
        {
            get { return origemVotosSA_; }
            set { origemVotosSA_ = value;  }
        }
  
        private System.Collections.Generic.ICollection<VotosCargo> votosCargos_;
        
		[ASN1SequenceOf(Name = "votosCargos", IsSetOf = false)]
    
		[ASN1Element(Name = "votosCargos", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<VotosCargo> VotosCargos
        {
            get { return votosCargos_; }
            set { votosCargos_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(EleicaoSA));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
