
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "IdentificacaoUrna")]
    public class IdentificacaoUrna : IASN1PreparedElement 
    {
        
        private IdentificacaoSecaoEleitoral identificacaoSecaoEleitoral_;
        private bool  identificacaoSecaoEleitoral_selected = false;

        
		[ASN1Element(Name = "identificacaoSecaoEleitoral", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public IdentificacaoSecaoEleitoral IdentificacaoSecaoEleitoral
        {
            get { return identificacaoSecaoEleitoral_; }
            set { selectIdentificacaoSecaoEleitoral(value); }
        }
  
        private IdentificacaoContingencia identificacaoContingencia_;
        private bool  identificacaoContingencia_selected = false;

        
		[ASN1Element(Name = "identificacaoContingencia", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public IdentificacaoContingencia IdentificacaoContingencia
        {
            get { return identificacaoContingencia_; }
            set { selectIdentificacaoContingencia(value); }
        }
  
        public bool isIdentificacaoSecaoEleitoralSelected()
        {
            return this.identificacaoSecaoEleitoral_selected;
        }

        

        public void selectIdentificacaoSecaoEleitoral (IdentificacaoSecaoEleitoral val) 
        {
            this.identificacaoSecaoEleitoral_ = val;
            this.identificacaoSecaoEleitoral_selected = true;
            
            this.identificacaoContingencia_selected = false;
            
        }
  
        public bool isIdentificacaoContingenciaSelected()
        {
            return this.identificacaoContingencia_selected;
        }

        

        public void selectIdentificacaoContingencia (IdentificacaoContingencia val) 
        {
            this.identificacaoContingencia_ = val;
            this.identificacaoContingencia_selected = true;
            
            this.identificacaoSecaoEleitoral_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(IdentificacaoUrna));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
