
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "MotivoApuracaoMistaComBU")]
    public class MotivoApuracaoMistaComBU : IASN1PreparedElement 
    {
        public enum EnumType 
        {
            
            [ASN1EnumItem ( Name = "urnaDataHoraIncorreta", HasTag = true , Tag = 1 )]
            urnaDataHoraIncorreta , 
            [ASN1EnumItem ( Name = "urnaComDefeito", HasTag = true , Tag = 2 )]
            urnaComDefeito , 
            [ASN1EnumItem ( Name = "urnaOutrasecao", HasTag = true , Tag = 3 )]
            urnaOutrasecao , 
            [ASN1EnumItem ( Name = "urnaPreparadaIncorretamente", HasTag = true , Tag = 4 )]
            urnaPreparadaIncorretamente , 
            [ASN1EnumItem ( Name = "urnaChegouAposInicioVotacao", HasTag = true , Tag = 5 )]
            urnaChegouAposInicioVotacao , 
            [ASN1EnumItem ( Name = "outros", HasTag = true , Tag = 99 )]
            outros , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(MotivoApuracaoMistaComBU));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
