
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "MotivoApuracaoMistaComMR")]
    public class MotivoApuracaoMistaComMR : IASN1PreparedElement 
    {
        public enum EnumType 
        {
            
            [ASN1EnumItem ( Name = "naoObteveExitoContingencia", HasTag = true , Tag = 1 )]
            naoObteveExitoContingencia , 
            [ASN1EnumItem ( Name = "indisponibilidadeUrnaContingencia", HasTag = true , Tag = 2 )]
            indisponibilidadeUrnaContingencia , 
            [ASN1EnumItem ( Name = "indisponibilidadeFlashContingencia", HasTag = true , Tag = 3 )]
            indisponibilidadeFlashContingencia , 
            [ASN1EnumItem ( Name = "problemaEnergiaEletrica", HasTag = true , Tag = 4 )]
            problemaEnergiaEletrica , 
            [ASN1EnumItem ( Name = "naoFoiPossivelTrocarUrna", HasTag = true , Tag = 5 )]
            naoFoiPossivelTrocarUrna , 
            [ASN1EnumItem ( Name = "naoFoiSolicitadaTrocaUrna", HasTag = true , Tag = 6 )]
            naoFoiSolicitadaTrocaUrna , 
            [ASN1EnumItem ( Name = "outros", HasTag = true , Tag = 99 )]
            outros , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(MotivoApuracaoMistaComMR));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
