
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "TipoUrna")]
    public class TipoUrna : IASN1PreparedElement 
    {
        public enum EnumType 
        {
            
            [ASN1EnumItem ( Name = "secao", HasTag = true , Tag = 1 )]
            secao , 
            [ASN1EnumItem ( Name = "contingencia", HasTag = true , Tag = 3 )]
            contingencia , 
            [ASN1EnumItem ( Name = "reservaSecao", HasTag = true , Tag = 4 )]
            reservaSecao , 
            [ASN1EnumItem ( Name = "reservaEncerrandoSecao", HasTag = true , Tag = 6 )]
            reservaEncerrandoSecao , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TipoUrna));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
