
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "TipoVoto")]
    public class TipoVoto : IASN1PreparedElement 
    {
        public enum EnumType 
        {
            
            [ASN1EnumItem ( Name = "legenda", HasTag = true , Tag = 1 )]
            legenda , 
            [ASN1EnumItem ( Name = "nominal", HasTag = true , Tag = 2 )]
            nominal , 
            [ASN1EnumItem ( Name = "branco", HasTag = true , Tag = 3 )]
            branco , 
            [ASN1EnumItem ( Name = "nulo", HasTag = true , Tag = 4 )]
            nulo , 
            [ASN1EnumItem ( Name = "brancoAposSuspensao", HasTag = true , Tag = 5 )]
            brancoAposSuspensao , 
            [ASN1EnumItem ( Name = "nuloAposSuspensao", HasTag = true , Tag = 6 )]
            nuloAposSuspensao , 
            [ASN1EnumItem ( Name = "nuloPorRepeticao", HasTag = true , Tag = 7 )]
            nuloPorRepeticao , 
            [ASN1EnumItem ( Name = "nuloCargoSemCandidato", HasTag = true , Tag = 8 )]
            nuloCargoSemCandidato , 
            [ASN1EnumItem ( Name = "nuloAposSuspensaoCargoSemCandidato", HasTag = true , Tag = 9 )]
            nuloAposSuspensaoCargoSemCandidato
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TipoVoto));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
