
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "Voto", IsSet = false)]
    public class Voto : IASN1PreparedElement 
    {
        
        private TipoVoto tipoVoto_;
        
		[ASN1Element(Name = "tipoVoto", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public TipoVoto TipoVoto
        {
            get { return tipoVoto_; }
            set { tipoVoto_ = value;  }
        }
  
        private VotoDigitado digitacao_;
        
        private bool  digitacao_present = false;
        
		[ASN1Element(Name = "digitacao", IsOptional = true, HasTag = false, HasDefaultValue = false)]
        public VotoDigitado Digitacao
        {
            get { return digitacao_; }
            set { digitacao_ = value; digitacao_present = true;  }
        }
  
        public bool isDigitacaoPresent()
        {
            return this.digitacao_present == true;
        }
        

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Voto));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
