
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSERDV {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "VotosCargo", IsSet = false)]
    public class VotosCargo : IASN1PreparedElement 
    {
        
        private CodigoCargoConsulta idCargo_;
        
		[ASN1Element(Name = "idCargo", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public CodigoCargoConsulta IdCargo
        {
            get { return idCargo_; }
            set { idCargo_ = value;  }
        }
  
        private QuantidadeEscolhas quantidadeEscolhas_;
        
		[ASN1Element(Name = "quantidadeEscolhas", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public QuantidadeEscolhas QuantidadeEscolhas
        {
            get { return quantidadeEscolhas_; }
            set { quantidadeEscolhas_ = value;  }
        }
  
        private System.Collections.Generic.ICollection<Voto> votos_;
        
		[ASN1SequenceOf(Name = "votos", IsSetOf = false)]
    
		[ASN1Element(Name = "votos", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<Voto> Votos
        {
            get { return votos_; }
            set { votos_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VotosCargo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
