
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSEBU {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "DadosSecao", IsSet = false)]
    public class DadosSecao : IASN1PreparedElement 
    {
        
        private DataHoraJE dataHoraAbertura_;
        
		[ASN1Element(Name = "dataHoraAbertura", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public DataHoraJE DataHoraAbertura
        {
            get { return dataHoraAbertura_; }
            set { dataHoraAbertura_ = value;  }
        }
  
        private DataHoraJE dataHoraEncerramento_;
        
		[ASN1Element(Name = "dataHoraEncerramento", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public DataHoraJE DataHoraEncerramento
        {
            get { return dataHoraEncerramento_; }
            set { dataHoraEncerramento_ = value;  }
        }
  
        private DataHoraJE dataHoraDesligamentoVotoImpresso_;
        
        private bool  dataHoraDesligamentoVotoImpresso_present = false;
        
		[ASN1Element(Name = "dataHoraDesligamentoVotoImpresso", IsOptional = true, HasTag = false, HasDefaultValue = false)]
        public DataHoraJE DataHoraDesligamentoVotoImpresso
        {
            get { return dataHoraDesligamentoVotoImpresso_; }
            set { dataHoraDesligamentoVotoImpresso_ = value; dataHoraDesligamentoVotoImpresso_present = true;  }
        }
  
        public bool isDataHoraDesligamentoVotoImpressoPresent()
        {
            return this.dataHoraDesligamentoVotoImpresso_present == true;
        }
        

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DadosSecao));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
