
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSEBU {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "IDEleitoral")]
    public class IDEleitoral : IASN1PreparedElement 
    {
        
        private IDProcessoEleitoral idProcessoEleitoral_;
        private bool  idProcessoEleitoral_selected = false;

        
		[ASN1Element(Name = "idProcessoEleitoral", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public IDProcessoEleitoral IdProcessoEleitoral
        {
            get { return idProcessoEleitoral_; }
            set { selectIdProcessoEleitoral(value); }
        }
  
        private IDPleito idPleito_;
        private bool  idPleito_selected = false;

        
		[ASN1Element(Name = "idPleito", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]
        public IDPleito IdPleito
        {
            get { return idPleito_; }
            set { selectIdPleito(value); }
        }
  
        private IDEleicao idEleicao_;
        private bool  idEleicao_selected = false;

        
		[ASN1Element(Name = "idEleicao", IsOptional = false, HasTag = true, Tag = 3, HasDefaultValue = false)]
        public IDEleicao IdEleicao
        {
            get { return idEleicao_; }
            set { selectIdEleicao(value); }
        }
  
        public bool isIdProcessoEleitoralSelected()
        {
            return this.idProcessoEleitoral_selected;
        }

        

        public void selectIdProcessoEleitoral (IDProcessoEleitoral val) 
        {
            this.idProcessoEleitoral_ = val;
            this.idProcessoEleitoral_selected = true;
            
            this.idPleito_selected = false;
            
            this.idEleicao_selected = false;
            
        }
  
        public bool isIdPleitoSelected()
        {
            return this.idPleito_selected;
        }

        

        public void selectIdPleito (IDPleito val) 
        {
            this.idPleito_ = val;
            this.idPleito_selected = true;
            
            this.idProcessoEleitoral_selected = false;
            
            this.idEleicao_selected = false;
            
        }
  
        public bool isIdEleicaoSelected()
        {
            return this.idEleicao_selected;
        }

        

        public void selectIdEleicao (IDEleicao val) 
        {
            this.idEleicao_ = val;
            this.idEleicao_selected = true;
            
            this.idProcessoEleitoral_selected = false;
            
            this.idPleito_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(IDEleitoral));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
