
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSEBU {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "IdentificacaoMesaJustificativa", IsSet = false)]
    public class IdentificacaoMesaJustificativa : IASN1PreparedElement 
    {
        
        private MunicipioZona municipioZona_;
        
		[ASN1Element(Name = "municipioZona", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public MunicipioZona MunicipioZona
        {
            get { return municipioZona_; }
            set { municipioZona_ = value;  }
        }
  
        private NumeroMesa mesa_;
        
		[ASN1Element(Name = "mesa", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public NumeroMesa Mesa
        {
            get { return mesa_; }
            set { mesa_ = value;  }
        }
  
        private NumeroUrna urna_;
        
		[ASN1Element(Name = "urna", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public NumeroUrna Urna
        {
            get { return urna_; }
            set { urna_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(IdentificacaoMesaJustificativa));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
