
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSEBU {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "ResultadoVotacaoPorEleicao", IsSet = false)]
    public class ResultadoVotacaoPorEleicao : IASN1PreparedElement 
    {
        
        private IDEleicao idEleicao_;
        
		[ASN1Element(Name = "idEleicao", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public IDEleicao IdEleicao
        {
            get { return idEleicao_; }
            set { idEleicao_ = value;  }
        }
  
        private QtdEleitores qtdEleitoresAptos_;
        
		[ASN1Element(Name = "qtdEleitoresAptos", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public QtdEleitores QtdEleitoresAptos
        {
            get { return qtdEleitoresAptos_; }
            set { qtdEleitoresAptos_ = value;  }
        }
  
        private System.Collections.Generic.ICollection<ResultadoVotacao> resultadosVotacao_;
        
		[ASN1SequenceOf(Name = "resultadosVotacao", IsSetOf = false)]
    
		[ASN1Element(Name = "resultadosVotacao", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<ResultadoVotacao> ResultadosVotacao
        {
            get { return resultadosVotacao_; }
            set { resultadosVotacao_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ResultadoVotacaoPorEleicao));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
