
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSEBU {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "TipoApuracao")]
    public class TipoApuracao : IASN1PreparedElement 
    {
        public enum EnumType 
        {
            
            [ASN1EnumItem ( Name = "totalmenteManual", HasTag = true , Tag = 1 )]
            totalmenteManual , 
            [ASN1EnumItem ( Name = "totalmenteEletronica", HasTag = true , Tag = 2 )]
            totalmenteEletronica , 
            [ASN1EnumItem ( Name = "mistaBU", HasTag = true , Tag = 3 )]
            mistaBU , 
            [ASN1EnumItem ( Name = "mistaMR", HasTag = true , Tag = 4 )]
            mistaMR , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TipoApuracao));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
