
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSEBU {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "TipoEnvelope")]
    public class TipoEnvelope : IASN1PreparedElement 
    {
        public enum EnumType 
        {
            
            [ASN1EnumItem ( Name = "envelopeBoletimUrna", HasTag = true , Tag = 1 )]
            envelopeBoletimUrna , 
            [ASN1EnumItem ( Name = "envelopeRegistroDigitalVoto", HasTag = true , Tag = 2 )]
            envelopeRegistroDigitalVoto , 
            [ASN1EnumItem ( Name = "envelopeBoletimUrnaImpresso", HasTag = true , Tag = 4 )]
            envelopeBoletimUrnaImpresso , 
            [ASN1EnumItem ( Name = "envelopeImagemBiometria", HasTag = true , Tag = 5 )]
            envelopeImagemBiometria , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TipoEnvelope));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
