
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSEBU {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "TotalVotosCargo", IsSet = false)]
    public class TotalVotosCargo : IASN1PreparedElement 
    {
        
        private CodigoCargoConsulta codigoCargo_;
        
		[ASN1Element(Name = "codigoCargo", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public CodigoCargoConsulta CodigoCargo
        {
            get { return codigoCargo_; }
            set { codigoCargo_ = value;  }
        }
  
        private int ordemImpressao_;
        [ASN1Integer( Name = "" )]
    
		[ASN1ValueRangeConstraint(Min = 1, Max = 99)]
		[ASN1Element(Name = "ordemImpressao", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public int OrdemImpressao
        {
            get { return ordemImpressao_; }
            set { ordemImpressao_ = value;  }
        }
  
        private System.Collections.Generic.ICollection<TotalVotosVotavel> votosVotaveis_;
        
		[ASN1SequenceOf(Name = "votosVotaveis", IsSetOf = false)]
    
		[ASN1Element(Name = "votosVotaveis", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<TotalVotosVotavel> VotosVotaveis
        {
            get { return votosVotaveis_; }
            set { votosVotaveis_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TotalVotosCargo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
