
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace TSEBU {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "TotalVotosVotavel", IsSet = false)]
    public class TotalVotosVotavel : IASN1PreparedElement 
    {
        
        private TipoVoto tipoVoto_;
        
		[ASN1Element(Name = "tipoVoto", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public TipoVoto TipoVoto
        {
            get { return tipoVoto_; }
            set { tipoVoto_ = value;  }
        }
  
        private QtdEleitores quantidadeVotos_;
        
		[ASN1Element(Name = "quantidadeVotos", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]
        public QtdEleitores QuantidadeVotos
        {
            get { return quantidadeVotos_; }
            set { quantidadeVotos_ = value;  }
        }
  
        private IdentificacaoVotavel identificacaoVotavel_;
        
        private bool  identificacaoVotavel_present = false;
        
		[ASN1Element(Name = "identificacaoVotavel", IsOptional = true, HasTag = true, Tag = 3, HasDefaultValue = false)]
        public IdentificacaoVotavel IdentificacaoVotavel
        {
            get { return identificacaoVotavel_; }
            set { identificacaoVotavel_ = value; identificacaoVotavel_present = true;  }
        }
  
        private byte[] assinatura_;
        [ASN1OctetString( Name = "" )]
    
		[ASN1Element(Name = "assinatura", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public byte[] Assinatura
        {
            get { return assinatura_; }
            set { assinatura_ = value;  }
        }
  
        public bool isIdentificacaoVotavelPresent()
        {
            return this.identificacaoVotavel_present == true;
        }
        

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TotalVotosVotavel));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
